name: Upstream Sync

on:
  schedule:
    - cron: "37 * * * *" # temp run every hour
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.3
        with:
          target_sync_branch: auto-ssh-age
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          upstream_sync_repo: Mic92/sops-nix
          upstream_sync_branch: master
          git_config_pull_rebase: "true"
          target_branch_push_args: "--force-with-lease"
